// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tempestvideo/v1/api.proto

// The public TempestVideo API: everything but super admin, and what the
// public SDKs are generated from. Callers authenticate with an AuthKit
// access token or an API key ("Authorization: Bearer <token>"), and each
// method checks their role on the tenant or installation it touches.
//
// Published as a contract: add fields and methods freely, but never rename,
// renumber or remove them. That needs a v2.

package tempestvideov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	tempestvideov1 "github.com/tempestvideo/go-sdk/tempestvideov1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProfileServiceName is the fully-qualified name of the ProfileService service.
	ProfileServiceName = "tempestvideo.v1.ProfileService"
	// TenantsServiceName is the fully-qualified name of the TenantsService service.
	TenantsServiceName = "tempestvideo.v1.TenantsService"
	// InstallationsServiceName is the fully-qualified name of the InstallationsService service.
	InstallationsServiceName = "tempestvideo.v1.InstallationsService"
	// MembersServiceName is the fully-qualified name of the MembersService service.
	MembersServiceName = "tempestvideo.v1.MembersService"
	// ConnectorsServiceName is the fully-qualified name of the ConnectorsService service.
	ConnectorsServiceName = "tempestvideo.v1.ConnectorsService"
	// ChannelsServiceName is the fully-qualified name of the ChannelsService service.
	ChannelsServiceName = "tempestvideo.v1.ChannelsService"
	// DevicesServiceName is the fully-qualified name of the DevicesService service.
	DevicesServiceName = "tempestvideo.v1.DevicesService"
	// ApiKeysServiceName is the fully-qualified name of the ApiKeysService service.
	ApiKeysServiceName = "tempestvideo.v1.ApiKeysService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProfileServiceUpsertProfileProcedure is the fully-qualified name of the ProfileService's
	// UpsertProfile RPC.
	ProfileServiceUpsertProfileProcedure = "/tempestvideo.v1.ProfileService/UpsertProfile"
	// TenantsServiceListTenantsProcedure is the fully-qualified name of the TenantsService's
	// ListTenants RPC.
	TenantsServiceListTenantsProcedure = "/tempestvideo.v1.TenantsService/ListTenants"
	// TenantsServiceUpdateTenantProcedure is the fully-qualified name of the TenantsService's
	// UpdateTenant RPC.
	TenantsServiceUpdateTenantProcedure = "/tempestvideo.v1.TenantsService/UpdateTenant"
	// InstallationsServiceListInstallationsProcedure is the fully-qualified name of the
	// InstallationsService's ListInstallations RPC.
	InstallationsServiceListInstallationsProcedure = "/tempestvideo.v1.InstallationsService/ListInstallations"
	// InstallationsServiceGetInstallationProcedure is the fully-qualified name of the
	// InstallationsService's GetInstallation RPC.
	InstallationsServiceGetInstallationProcedure = "/tempestvideo.v1.InstallationsService/GetInstallation"
	// InstallationsServiceCreateInstallationProcedure is the fully-qualified name of the
	// InstallationsService's CreateInstallation RPC.
	InstallationsServiceCreateInstallationProcedure = "/tempestvideo.v1.InstallationsService/CreateInstallation"
	// InstallationsServiceUpdateInstallationProcedure is the fully-qualified name of the
	// InstallationsService's UpdateInstallation RPC.
	InstallationsServiceUpdateInstallationProcedure = "/tempestvideo.v1.InstallationsService/UpdateInstallation"
	// InstallationsServiceDeleteInstallationProcedure is the fully-qualified name of the
	// InstallationsService's DeleteInstallation RPC.
	InstallationsServiceDeleteInstallationProcedure = "/tempestvideo.v1.InstallationsService/DeleteInstallation"
	// MembersServiceListTenantAdminsProcedure is the fully-qualified name of the MembersService's
	// ListTenantAdmins RPC.
	MembersServiceListTenantAdminsProcedure = "/tempestvideo.v1.MembersService/ListTenantAdmins"
	// MembersServiceAddTenantAdminProcedure is the fully-qualified name of the MembersService's
	// AddTenantAdmin RPC.
	MembersServiceAddTenantAdminProcedure = "/tempestvideo.v1.MembersService/AddTenantAdmin"
	// MembersServiceRemoveTenantAdminProcedure is the fully-qualified name of the MembersService's
	// RemoveTenantAdmin RPC.
	MembersServiceRemoveTenantAdminProcedure = "/tempestvideo.v1.MembersService/RemoveTenantAdmin"
	// MembersServiceListInstallationMembersProcedure is the fully-qualified name of the
	// MembersService's ListInstallationMembers RPC.
	MembersServiceListInstallationMembersProcedure = "/tempestvideo.v1.MembersService/ListInstallationMembers"
	// MembersServiceAddInstallationMemberProcedure is the fully-qualified name of the MembersService's
	// AddInstallationMember RPC.
	MembersServiceAddInstallationMemberProcedure = "/tempestvideo.v1.MembersService/AddInstallationMember"
	// MembersServiceUpdateInstallationMemberProcedure is the fully-qualified name of the
	// MembersService's UpdateInstallationMember RPC.
	MembersServiceUpdateInstallationMemberProcedure = "/tempestvideo.v1.MembersService/UpdateInstallationMember"
	// MembersServiceRemoveInstallationMemberProcedure is the fully-qualified name of the
	// MembersService's RemoveInstallationMember RPC.
	MembersServiceRemoveInstallationMemberProcedure = "/tempestvideo.v1.MembersService/RemoveInstallationMember"
	// MembersServiceUpdatePendingAccessProcedure is the fully-qualified name of the MembersService's
	// UpdatePendingAccess RPC.
	MembersServiceUpdatePendingAccessProcedure = "/tempestvideo.v1.MembersService/UpdatePendingAccess"
	// MembersServiceCancelPendingAccessProcedure is the fully-qualified name of the MembersService's
	// CancelPendingAccess RPC.
	MembersServiceCancelPendingAccessProcedure = "/tempestvideo.v1.MembersService/CancelPendingAccess"
	// ConnectorsServiceListConnectorsProcedure is the fully-qualified name of the ConnectorsService's
	// ListConnectors RPC.
	ConnectorsServiceListConnectorsProcedure = "/tempestvideo.v1.ConnectorsService/ListConnectors"
	// ConnectorsServiceCreateInstallationConnectorProcedure is the fully-qualified name of the
	// ConnectorsService's CreateInstallationConnector RPC.
	ConnectorsServiceCreateInstallationConnectorProcedure = "/tempestvideo.v1.ConnectorsService/CreateInstallationConnector"
	// ConnectorsServiceRenameConnectorProcedure is the fully-qualified name of the ConnectorsService's
	// RenameConnector RPC.
	ConnectorsServiceRenameConnectorProcedure = "/tempestvideo.v1.ConnectorsService/RenameConnector"
	// ConnectorsServiceRegenerateLicenseKeyProcedure is the fully-qualified name of the
	// ConnectorsService's RegenerateLicenseKey RPC.
	ConnectorsServiceRegenerateLicenseKeyProcedure = "/tempestvideo.v1.ConnectorsService/RegenerateLicenseKey"
	// ConnectorsServiceRevokeConnectorProcedure is the fully-qualified name of the ConnectorsService's
	// RevokeConnector RPC.
	ConnectorsServiceRevokeConnectorProcedure = "/tempestvideo.v1.ConnectorsService/RevokeConnector"
	// ConnectorsServiceDeleteConnectorProcedure is the fully-qualified name of the ConnectorsService's
	// DeleteConnector RPC.
	ConnectorsServiceDeleteConnectorProcedure = "/tempestvideo.v1.ConnectorsService/DeleteConnector"
	// ChannelsServiceListChannelsProcedure is the fully-qualified name of the ChannelsService's
	// ListChannels RPC.
	ChannelsServiceListChannelsProcedure = "/tempestvideo.v1.ChannelsService/ListChannels"
	// ChannelsServiceCreateChannelProcedure is the fully-qualified name of the ChannelsService's
	// CreateChannel RPC.
	ChannelsServiceCreateChannelProcedure = "/tempestvideo.v1.ChannelsService/CreateChannel"
	// ChannelsServiceUpdateChannelProcedure is the fully-qualified name of the ChannelsService's
	// UpdateChannel RPC.
	ChannelsServiceUpdateChannelProcedure = "/tempestvideo.v1.ChannelsService/UpdateChannel"
	// ChannelsServiceDeleteChannelProcedure is the fully-qualified name of the ChannelsService's
	// DeleteChannel RPC.
	ChannelsServiceDeleteChannelProcedure = "/tempestvideo.v1.ChannelsService/DeleteChannel"
	// ChannelsServiceSetChannelIconProcedure is the fully-qualified name of the ChannelsService's
	// SetChannelIcon RPC.
	ChannelsServiceSetChannelIconProcedure = "/tempestvideo.v1.ChannelsService/SetChannelIcon"
	// ChannelsServiceDeleteChannelIconProcedure is the fully-qualified name of the ChannelsService's
	// DeleteChannelIcon RPC.
	ChannelsServiceDeleteChannelIconProcedure = "/tempestvideo.v1.ChannelsService/DeleteChannelIcon"
	// DevicesServiceListDevicesProcedure is the fully-qualified name of the DevicesService's
	// ListDevices RPC.
	DevicesServiceListDevicesProcedure = "/tempestvideo.v1.DevicesService/ListDevices"
	// DevicesServiceCreateDeviceProcedure is the fully-qualified name of the DevicesService's
	// CreateDevice RPC.
	DevicesServiceCreateDeviceProcedure = "/tempestvideo.v1.DevicesService/CreateDevice"
	// DevicesServiceUpdateDeviceProcedure is the fully-qualified name of the DevicesService's
	// UpdateDevice RPC.
	DevicesServiceUpdateDeviceProcedure = "/tempestvideo.v1.DevicesService/UpdateDevice"
	// DevicesServiceDeleteDeviceProcedure is the fully-qualified name of the DevicesService's
	// DeleteDevice RPC.
	DevicesServiceDeleteDeviceProcedure = "/tempestvideo.v1.DevicesService/DeleteDevice"
	// DevicesServiceSetDeviceChannelProcedure is the fully-qualified name of the DevicesService's
	// SetDeviceChannel RPC.
	DevicesServiceSetDeviceChannelProcedure = "/tempestvideo.v1.DevicesService/SetDeviceChannel"
	// DevicesServiceGetChannelRequestProcedure is the fully-qualified name of the DevicesService's
	// GetChannelRequest RPC.
	DevicesServiceGetChannelRequestProcedure = "/tempestvideo.v1.DevicesService/GetChannelRequest"
	// DevicesServiceProvisionDeviceProcedure is the fully-qualified name of the DevicesService's
	// ProvisionDevice RPC.
	DevicesServiceProvisionDeviceProcedure = "/tempestvideo.v1.DevicesService/ProvisionDevice"
	// DevicesServiceGetDeviceTaskProcedure is the fully-qualified name of the DevicesService's
	// GetDeviceTask RPC.
	DevicesServiceGetDeviceTaskProcedure = "/tempestvideo.v1.DevicesService/GetDeviceTask"
	// ApiKeysServiceCreateApiKeyProcedure is the fully-qualified name of the ApiKeysService's
	// CreateApiKey RPC.
	ApiKeysServiceCreateApiKeyProcedure = "/tempestvideo.v1.ApiKeysService/CreateApiKey"
	// ApiKeysServiceListApiKeysProcedure is the fully-qualified name of the ApiKeysService's
	// ListApiKeys RPC.
	ApiKeysServiceListApiKeysProcedure = "/tempestvideo.v1.ApiKeysService/ListApiKeys"
	// ApiKeysServiceDeleteApiKeyProcedure is the fully-qualified name of the ApiKeysService's
	// DeleteApiKey RPC.
	ApiKeysServiceDeleteApiKeyProcedure = "/tempestvideo.v1.ApiKeysService/DeleteApiKey"
)

// ProfileServiceClient is a client for the tempestvideo.v1.ProfileService service.
type ProfileServiceClient interface {
	UpsertProfile(context.Context, *connect.Request[tempestvideov1.UpsertProfileRequest]) (*connect.Response[tempestvideov1.UpsertProfileResponse], error)
}

// NewProfileServiceClient constructs a client for the tempestvideo.v1.ProfileService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProfileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProfileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	profileServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ProfileService").Methods()
	return &profileServiceClient{
		upsertProfile: connect.NewClient[tempestvideov1.UpsertProfileRequest, tempestvideov1.UpsertProfileResponse](
			httpClient,
			baseURL+ProfileServiceUpsertProfileProcedure,
			connect.WithSchema(profileServiceMethods.ByName("UpsertProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// profileServiceClient implements ProfileServiceClient.
type profileServiceClient struct {
	upsertProfile *connect.Client[tempestvideov1.UpsertProfileRequest, tempestvideov1.UpsertProfileResponse]
}

// UpsertProfile calls tempestvideo.v1.ProfileService.UpsertProfile.
func (c *profileServiceClient) UpsertProfile(ctx context.Context, req *connect.Request[tempestvideov1.UpsertProfileRequest]) (*connect.Response[tempestvideov1.UpsertProfileResponse], error) {
	return c.upsertProfile.CallUnary(ctx, req)
}

// ProfileServiceHandler is an implementation of the tempestvideo.v1.ProfileService service.
type ProfileServiceHandler interface {
	UpsertProfile(context.Context, *connect.Request[tempestvideov1.UpsertProfileRequest]) (*connect.Response[tempestvideov1.UpsertProfileResponse], error)
}

// NewProfileServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProfileServiceHandler(svc ProfileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	profileServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ProfileService").Methods()
	profileServiceUpsertProfileHandler := connect.NewUnaryHandler(
		ProfileServiceUpsertProfileProcedure,
		svc.UpsertProfile,
		connect.WithSchema(profileServiceMethods.ByName("UpsertProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.ProfileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProfileServiceUpsertProfileProcedure:
			profileServiceUpsertProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProfileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProfileServiceHandler struct{}

func (UnimplementedProfileServiceHandler) UpsertProfile(context.Context, *connect.Request[tempestvideov1.UpsertProfileRequest]) (*connect.Response[tempestvideov1.UpsertProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ProfileService.UpsertProfile is not implemented"))
}

// TenantsServiceClient is a client for the tempestvideo.v1.TenantsService service.
type TenantsServiceClient interface {
	ListTenants(context.Context, *connect.Request[tempestvideov1.ListTenantsRequest]) (*connect.Response[tempestvideov1.ListTenantsResponse], error)
	UpdateTenant(context.Context, *connect.Request[tempestvideov1.UpdateTenantRequest]) (*connect.Response[tempestvideov1.UpdateTenantResponse], error)
}

// NewTenantsServiceClient constructs a client for the tempestvideo.v1.TenantsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTenantsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TenantsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tenantsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("TenantsService").Methods()
	return &tenantsServiceClient{
		listTenants: connect.NewClient[tempestvideov1.ListTenantsRequest, tempestvideov1.ListTenantsResponse](
			httpClient,
			baseURL+TenantsServiceListTenantsProcedure,
			connect.WithSchema(tenantsServiceMethods.ByName("ListTenants")),
			connect.WithClientOptions(opts...),
		),
		updateTenant: connect.NewClient[tempestvideov1.UpdateTenantRequest, tempestvideov1.UpdateTenantResponse](
			httpClient,
			baseURL+TenantsServiceUpdateTenantProcedure,
			connect.WithSchema(tenantsServiceMethods.ByName("UpdateTenant")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tenantsServiceClient implements TenantsServiceClient.
type tenantsServiceClient struct {
	listTenants  *connect.Client[tempestvideov1.ListTenantsRequest, tempestvideov1.ListTenantsResponse]
	updateTenant *connect.Client[tempestvideov1.UpdateTenantRequest, tempestvideov1.UpdateTenantResponse]
}

// ListTenants calls tempestvideo.v1.TenantsService.ListTenants.
func (c *tenantsServiceClient) ListTenants(ctx context.Context, req *connect.Request[tempestvideov1.ListTenantsRequest]) (*connect.Response[tempestvideov1.ListTenantsResponse], error) {
	return c.listTenants.CallUnary(ctx, req)
}

// UpdateTenant calls tempestvideo.v1.TenantsService.UpdateTenant.
func (c *tenantsServiceClient) UpdateTenant(ctx context.Context, req *connect.Request[tempestvideov1.UpdateTenantRequest]) (*connect.Response[tempestvideov1.UpdateTenantResponse], error) {
	return c.updateTenant.CallUnary(ctx, req)
}

// TenantsServiceHandler is an implementation of the tempestvideo.v1.TenantsService service.
type TenantsServiceHandler interface {
	ListTenants(context.Context, *connect.Request[tempestvideov1.ListTenantsRequest]) (*connect.Response[tempestvideov1.ListTenantsResponse], error)
	UpdateTenant(context.Context, *connect.Request[tempestvideov1.UpdateTenantRequest]) (*connect.Response[tempestvideov1.UpdateTenantResponse], error)
}

// NewTenantsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTenantsServiceHandler(svc TenantsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tenantsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("TenantsService").Methods()
	tenantsServiceListTenantsHandler := connect.NewUnaryHandler(
		TenantsServiceListTenantsProcedure,
		svc.ListTenants,
		connect.WithSchema(tenantsServiceMethods.ByName("ListTenants")),
		connect.WithHandlerOptions(opts...),
	)
	tenantsServiceUpdateTenantHandler := connect.NewUnaryHandler(
		TenantsServiceUpdateTenantProcedure,
		svc.UpdateTenant,
		connect.WithSchema(tenantsServiceMethods.ByName("UpdateTenant")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.TenantsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TenantsServiceListTenantsProcedure:
			tenantsServiceListTenantsHandler.ServeHTTP(w, r)
		case TenantsServiceUpdateTenantProcedure:
			tenantsServiceUpdateTenantHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTenantsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTenantsServiceHandler struct{}

func (UnimplementedTenantsServiceHandler) ListTenants(context.Context, *connect.Request[tempestvideov1.ListTenantsRequest]) (*connect.Response[tempestvideov1.ListTenantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.TenantsService.ListTenants is not implemented"))
}

func (UnimplementedTenantsServiceHandler) UpdateTenant(context.Context, *connect.Request[tempestvideov1.UpdateTenantRequest]) (*connect.Response[tempestvideov1.UpdateTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.TenantsService.UpdateTenant is not implemented"))
}

// InstallationsServiceClient is a client for the tempestvideo.v1.InstallationsService service.
type InstallationsServiceClient interface {
	ListInstallations(context.Context, *connect.Request[tempestvideov1.ListInstallationsRequest]) (*connect.Response[tempestvideov1.ListInstallationsResponse], error)
	GetInstallation(context.Context, *connect.Request[tempestvideov1.GetInstallationRequest]) (*connect.Response[tempestvideov1.GetInstallationResponse], error)
	CreateInstallation(context.Context, *connect.Request[tempestvideov1.CreateInstallationRequest]) (*connect.Response[tempestvideov1.CreateInstallationResponse], error)
	UpdateInstallation(context.Context, *connect.Request[tempestvideov1.UpdateInstallationRequest]) (*connect.Response[tempestvideov1.UpdateInstallationResponse], error)
	DeleteInstallation(context.Context, *connect.Request[tempestvideov1.DeleteInstallationRequest]) (*connect.Response[tempestvideov1.DeleteInstallationResponse], error)
}

// NewInstallationsServiceClient constructs a client for the tempestvideo.v1.InstallationsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInstallationsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InstallationsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	installationsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("InstallationsService").Methods()
	return &installationsServiceClient{
		listInstallations: connect.NewClient[tempestvideov1.ListInstallationsRequest, tempestvideov1.ListInstallationsResponse](
			httpClient,
			baseURL+InstallationsServiceListInstallationsProcedure,
			connect.WithSchema(installationsServiceMethods.ByName("ListInstallations")),
			connect.WithClientOptions(opts...),
		),
		getInstallation: connect.NewClient[tempestvideov1.GetInstallationRequest, tempestvideov1.GetInstallationResponse](
			httpClient,
			baseURL+InstallationsServiceGetInstallationProcedure,
			connect.WithSchema(installationsServiceMethods.ByName("GetInstallation")),
			connect.WithClientOptions(opts...),
		),
		createInstallation: connect.NewClient[tempestvideov1.CreateInstallationRequest, tempestvideov1.CreateInstallationResponse](
			httpClient,
			baseURL+InstallationsServiceCreateInstallationProcedure,
			connect.WithSchema(installationsServiceMethods.ByName("CreateInstallation")),
			connect.WithClientOptions(opts...),
		),
		updateInstallation: connect.NewClient[tempestvideov1.UpdateInstallationRequest, tempestvideov1.UpdateInstallationResponse](
			httpClient,
			baseURL+InstallationsServiceUpdateInstallationProcedure,
			connect.WithSchema(installationsServiceMethods.ByName("UpdateInstallation")),
			connect.WithClientOptions(opts...),
		),
		deleteInstallation: connect.NewClient[tempestvideov1.DeleteInstallationRequest, tempestvideov1.DeleteInstallationResponse](
			httpClient,
			baseURL+InstallationsServiceDeleteInstallationProcedure,
			connect.WithSchema(installationsServiceMethods.ByName("DeleteInstallation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// installationsServiceClient implements InstallationsServiceClient.
type installationsServiceClient struct {
	listInstallations  *connect.Client[tempestvideov1.ListInstallationsRequest, tempestvideov1.ListInstallationsResponse]
	getInstallation    *connect.Client[tempestvideov1.GetInstallationRequest, tempestvideov1.GetInstallationResponse]
	createInstallation *connect.Client[tempestvideov1.CreateInstallationRequest, tempestvideov1.CreateInstallationResponse]
	updateInstallation *connect.Client[tempestvideov1.UpdateInstallationRequest, tempestvideov1.UpdateInstallationResponse]
	deleteInstallation *connect.Client[tempestvideov1.DeleteInstallationRequest, tempestvideov1.DeleteInstallationResponse]
}

// ListInstallations calls tempestvideo.v1.InstallationsService.ListInstallations.
func (c *installationsServiceClient) ListInstallations(ctx context.Context, req *connect.Request[tempestvideov1.ListInstallationsRequest]) (*connect.Response[tempestvideov1.ListInstallationsResponse], error) {
	return c.listInstallations.CallUnary(ctx, req)
}

// GetInstallation calls tempestvideo.v1.InstallationsService.GetInstallation.
func (c *installationsServiceClient) GetInstallation(ctx context.Context, req *connect.Request[tempestvideov1.GetInstallationRequest]) (*connect.Response[tempestvideov1.GetInstallationResponse], error) {
	return c.getInstallation.CallUnary(ctx, req)
}

// CreateInstallation calls tempestvideo.v1.InstallationsService.CreateInstallation.
func (c *installationsServiceClient) CreateInstallation(ctx context.Context, req *connect.Request[tempestvideov1.CreateInstallationRequest]) (*connect.Response[tempestvideov1.CreateInstallationResponse], error) {
	return c.createInstallation.CallUnary(ctx, req)
}

// UpdateInstallation calls tempestvideo.v1.InstallationsService.UpdateInstallation.
func (c *installationsServiceClient) UpdateInstallation(ctx context.Context, req *connect.Request[tempestvideov1.UpdateInstallationRequest]) (*connect.Response[tempestvideov1.UpdateInstallationResponse], error) {
	return c.updateInstallation.CallUnary(ctx, req)
}

// DeleteInstallation calls tempestvideo.v1.InstallationsService.DeleteInstallation.
func (c *installationsServiceClient) DeleteInstallation(ctx context.Context, req *connect.Request[tempestvideov1.DeleteInstallationRequest]) (*connect.Response[tempestvideov1.DeleteInstallationResponse], error) {
	return c.deleteInstallation.CallUnary(ctx, req)
}

// InstallationsServiceHandler is an implementation of the tempestvideo.v1.InstallationsService
// service.
type InstallationsServiceHandler interface {
	ListInstallations(context.Context, *connect.Request[tempestvideov1.ListInstallationsRequest]) (*connect.Response[tempestvideov1.ListInstallationsResponse], error)
	GetInstallation(context.Context, *connect.Request[tempestvideov1.GetInstallationRequest]) (*connect.Response[tempestvideov1.GetInstallationResponse], error)
	CreateInstallation(context.Context, *connect.Request[tempestvideov1.CreateInstallationRequest]) (*connect.Response[tempestvideov1.CreateInstallationResponse], error)
	UpdateInstallation(context.Context, *connect.Request[tempestvideov1.UpdateInstallationRequest]) (*connect.Response[tempestvideov1.UpdateInstallationResponse], error)
	DeleteInstallation(context.Context, *connect.Request[tempestvideov1.DeleteInstallationRequest]) (*connect.Response[tempestvideov1.DeleteInstallationResponse], error)
}

// NewInstallationsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInstallationsServiceHandler(svc InstallationsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	installationsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("InstallationsService").Methods()
	installationsServiceListInstallationsHandler := connect.NewUnaryHandler(
		InstallationsServiceListInstallationsProcedure,
		svc.ListInstallations,
		connect.WithSchema(installationsServiceMethods.ByName("ListInstallations")),
		connect.WithHandlerOptions(opts...),
	)
	installationsServiceGetInstallationHandler := connect.NewUnaryHandler(
		InstallationsServiceGetInstallationProcedure,
		svc.GetInstallation,
		connect.WithSchema(installationsServiceMethods.ByName("GetInstallation")),
		connect.WithHandlerOptions(opts...),
	)
	installationsServiceCreateInstallationHandler := connect.NewUnaryHandler(
		InstallationsServiceCreateInstallationProcedure,
		svc.CreateInstallation,
		connect.WithSchema(installationsServiceMethods.ByName("CreateInstallation")),
		connect.WithHandlerOptions(opts...),
	)
	installationsServiceUpdateInstallationHandler := connect.NewUnaryHandler(
		InstallationsServiceUpdateInstallationProcedure,
		svc.UpdateInstallation,
		connect.WithSchema(installationsServiceMethods.ByName("UpdateInstallation")),
		connect.WithHandlerOptions(opts...),
	)
	installationsServiceDeleteInstallationHandler := connect.NewUnaryHandler(
		InstallationsServiceDeleteInstallationProcedure,
		svc.DeleteInstallation,
		connect.WithSchema(installationsServiceMethods.ByName("DeleteInstallation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.InstallationsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InstallationsServiceListInstallationsProcedure:
			installationsServiceListInstallationsHandler.ServeHTTP(w, r)
		case InstallationsServiceGetInstallationProcedure:
			installationsServiceGetInstallationHandler.ServeHTTP(w, r)
		case InstallationsServiceCreateInstallationProcedure:
			installationsServiceCreateInstallationHandler.ServeHTTP(w, r)
		case InstallationsServiceUpdateInstallationProcedure:
			installationsServiceUpdateInstallationHandler.ServeHTTP(w, r)
		case InstallationsServiceDeleteInstallationProcedure:
			installationsServiceDeleteInstallationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInstallationsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInstallationsServiceHandler struct{}

func (UnimplementedInstallationsServiceHandler) ListInstallations(context.Context, *connect.Request[tempestvideov1.ListInstallationsRequest]) (*connect.Response[tempestvideov1.ListInstallationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.InstallationsService.ListInstallations is not implemented"))
}

func (UnimplementedInstallationsServiceHandler) GetInstallation(context.Context, *connect.Request[tempestvideov1.GetInstallationRequest]) (*connect.Response[tempestvideov1.GetInstallationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.InstallationsService.GetInstallation is not implemented"))
}

func (UnimplementedInstallationsServiceHandler) CreateInstallation(context.Context, *connect.Request[tempestvideov1.CreateInstallationRequest]) (*connect.Response[tempestvideov1.CreateInstallationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.InstallationsService.CreateInstallation is not implemented"))
}

func (UnimplementedInstallationsServiceHandler) UpdateInstallation(context.Context, *connect.Request[tempestvideov1.UpdateInstallationRequest]) (*connect.Response[tempestvideov1.UpdateInstallationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.InstallationsService.UpdateInstallation is not implemented"))
}

func (UnimplementedInstallationsServiceHandler) DeleteInstallation(context.Context, *connect.Request[tempestvideov1.DeleteInstallationRequest]) (*connect.Response[tempestvideov1.DeleteInstallationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.InstallationsService.DeleteInstallation is not implemented"))
}

// MembersServiceClient is a client for the tempestvideo.v1.MembersService service.
type MembersServiceClient interface {
	ListTenantAdmins(context.Context, *connect.Request[tempestvideov1.ListTenantAdminsRequest]) (*connect.Response[tempestvideov1.ListTenantAdminsResponse], error)
	AddTenantAdmin(context.Context, *connect.Request[tempestvideov1.AddTenantAdminRequest]) (*connect.Response[tempestvideov1.AddTenantAdminResponse], error)
	RemoveTenantAdmin(context.Context, *connect.Request[tempestvideov1.RemoveTenantAdminRequest]) (*connect.Response[tempestvideov1.RemoveTenantAdminResponse], error)
	ListInstallationMembers(context.Context, *connect.Request[tempestvideov1.ListInstallationMembersRequest]) (*connect.Response[tempestvideov1.ListInstallationMembersResponse], error)
	AddInstallationMember(context.Context, *connect.Request[tempestvideov1.AddInstallationMemberRequest]) (*connect.Response[tempestvideov1.AddInstallationMemberResponse], error)
	UpdateInstallationMember(context.Context, *connect.Request[tempestvideov1.UpdateInstallationMemberRequest]) (*connect.Response[tempestvideov1.UpdateInstallationMemberResponse], error)
	RemoveInstallationMember(context.Context, *connect.Request[tempestvideov1.RemoveInstallationMemberRequest]) (*connect.Response[tempestvideov1.RemoveInstallationMemberResponse], error)
	UpdatePendingAccess(context.Context, *connect.Request[tempestvideov1.UpdatePendingAccessRequest]) (*connect.Response[tempestvideov1.UpdatePendingAccessResponse], error)
	CancelPendingAccess(context.Context, *connect.Request[tempestvideov1.CancelPendingAccessRequest]) (*connect.Response[tempestvideov1.CancelPendingAccessResponse], error)
}

// NewMembersServiceClient constructs a client for the tempestvideo.v1.MembersService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMembersServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MembersServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	membersServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("MembersService").Methods()
	return &membersServiceClient{
		listTenantAdmins: connect.NewClient[tempestvideov1.ListTenantAdminsRequest, tempestvideov1.ListTenantAdminsResponse](
			httpClient,
			baseURL+MembersServiceListTenantAdminsProcedure,
			connect.WithSchema(membersServiceMethods.ByName("ListTenantAdmins")),
			connect.WithClientOptions(opts...),
		),
		addTenantAdmin: connect.NewClient[tempestvideov1.AddTenantAdminRequest, tempestvideov1.AddTenantAdminResponse](
			httpClient,
			baseURL+MembersServiceAddTenantAdminProcedure,
			connect.WithSchema(membersServiceMethods.ByName("AddTenantAdmin")),
			connect.WithClientOptions(opts...),
		),
		removeTenantAdmin: connect.NewClient[tempestvideov1.RemoveTenantAdminRequest, tempestvideov1.RemoveTenantAdminResponse](
			httpClient,
			baseURL+MembersServiceRemoveTenantAdminProcedure,
			connect.WithSchema(membersServiceMethods.ByName("RemoveTenantAdmin")),
			connect.WithClientOptions(opts...),
		),
		listInstallationMembers: connect.NewClient[tempestvideov1.ListInstallationMembersRequest, tempestvideov1.ListInstallationMembersResponse](
			httpClient,
			baseURL+MembersServiceListInstallationMembersProcedure,
			connect.WithSchema(membersServiceMethods.ByName("ListInstallationMembers")),
			connect.WithClientOptions(opts...),
		),
		addInstallationMember: connect.NewClient[tempestvideov1.AddInstallationMemberRequest, tempestvideov1.AddInstallationMemberResponse](
			httpClient,
			baseURL+MembersServiceAddInstallationMemberProcedure,
			connect.WithSchema(membersServiceMethods.ByName("AddInstallationMember")),
			connect.WithClientOptions(opts...),
		),
		updateInstallationMember: connect.NewClient[tempestvideov1.UpdateInstallationMemberRequest, tempestvideov1.UpdateInstallationMemberResponse](
			httpClient,
			baseURL+MembersServiceUpdateInstallationMemberProcedure,
			connect.WithSchema(membersServiceMethods.ByName("UpdateInstallationMember")),
			connect.WithClientOptions(opts...),
		),
		removeInstallationMember: connect.NewClient[tempestvideov1.RemoveInstallationMemberRequest, tempestvideov1.RemoveInstallationMemberResponse](
			httpClient,
			baseURL+MembersServiceRemoveInstallationMemberProcedure,
			connect.WithSchema(membersServiceMethods.ByName("RemoveInstallationMember")),
			connect.WithClientOptions(opts...),
		),
		updatePendingAccess: connect.NewClient[tempestvideov1.UpdatePendingAccessRequest, tempestvideov1.UpdatePendingAccessResponse](
			httpClient,
			baseURL+MembersServiceUpdatePendingAccessProcedure,
			connect.WithSchema(membersServiceMethods.ByName("UpdatePendingAccess")),
			connect.WithClientOptions(opts...),
		),
		cancelPendingAccess: connect.NewClient[tempestvideov1.CancelPendingAccessRequest, tempestvideov1.CancelPendingAccessResponse](
			httpClient,
			baseURL+MembersServiceCancelPendingAccessProcedure,
			connect.WithSchema(membersServiceMethods.ByName("CancelPendingAccess")),
			connect.WithClientOptions(opts...),
		),
	}
}

// membersServiceClient implements MembersServiceClient.
type membersServiceClient struct {
	listTenantAdmins         *connect.Client[tempestvideov1.ListTenantAdminsRequest, tempestvideov1.ListTenantAdminsResponse]
	addTenantAdmin           *connect.Client[tempestvideov1.AddTenantAdminRequest, tempestvideov1.AddTenantAdminResponse]
	removeTenantAdmin        *connect.Client[tempestvideov1.RemoveTenantAdminRequest, tempestvideov1.RemoveTenantAdminResponse]
	listInstallationMembers  *connect.Client[tempestvideov1.ListInstallationMembersRequest, tempestvideov1.ListInstallationMembersResponse]
	addInstallationMember    *connect.Client[tempestvideov1.AddInstallationMemberRequest, tempestvideov1.AddInstallationMemberResponse]
	updateInstallationMember *connect.Client[tempestvideov1.UpdateInstallationMemberRequest, tempestvideov1.UpdateInstallationMemberResponse]
	removeInstallationMember *connect.Client[tempestvideov1.RemoveInstallationMemberRequest, tempestvideov1.RemoveInstallationMemberResponse]
	updatePendingAccess      *connect.Client[tempestvideov1.UpdatePendingAccessRequest, tempestvideov1.UpdatePendingAccessResponse]
	cancelPendingAccess      *connect.Client[tempestvideov1.CancelPendingAccessRequest, tempestvideov1.CancelPendingAccessResponse]
}

// ListTenantAdmins calls tempestvideo.v1.MembersService.ListTenantAdmins.
func (c *membersServiceClient) ListTenantAdmins(ctx context.Context, req *connect.Request[tempestvideov1.ListTenantAdminsRequest]) (*connect.Response[tempestvideov1.ListTenantAdminsResponse], error) {
	return c.listTenantAdmins.CallUnary(ctx, req)
}

// AddTenantAdmin calls tempestvideo.v1.MembersService.AddTenantAdmin.
func (c *membersServiceClient) AddTenantAdmin(ctx context.Context, req *connect.Request[tempestvideov1.AddTenantAdminRequest]) (*connect.Response[tempestvideov1.AddTenantAdminResponse], error) {
	return c.addTenantAdmin.CallUnary(ctx, req)
}

// RemoveTenantAdmin calls tempestvideo.v1.MembersService.RemoveTenantAdmin.
func (c *membersServiceClient) RemoveTenantAdmin(ctx context.Context, req *connect.Request[tempestvideov1.RemoveTenantAdminRequest]) (*connect.Response[tempestvideov1.RemoveTenantAdminResponse], error) {
	return c.removeTenantAdmin.CallUnary(ctx, req)
}

// ListInstallationMembers calls tempestvideo.v1.MembersService.ListInstallationMembers.
func (c *membersServiceClient) ListInstallationMembers(ctx context.Context, req *connect.Request[tempestvideov1.ListInstallationMembersRequest]) (*connect.Response[tempestvideov1.ListInstallationMembersResponse], error) {
	return c.listInstallationMembers.CallUnary(ctx, req)
}

// AddInstallationMember calls tempestvideo.v1.MembersService.AddInstallationMember.
func (c *membersServiceClient) AddInstallationMember(ctx context.Context, req *connect.Request[tempestvideov1.AddInstallationMemberRequest]) (*connect.Response[tempestvideov1.AddInstallationMemberResponse], error) {
	return c.addInstallationMember.CallUnary(ctx, req)
}

// UpdateInstallationMember calls tempestvideo.v1.MembersService.UpdateInstallationMember.
func (c *membersServiceClient) UpdateInstallationMember(ctx context.Context, req *connect.Request[tempestvideov1.UpdateInstallationMemberRequest]) (*connect.Response[tempestvideov1.UpdateInstallationMemberResponse], error) {
	return c.updateInstallationMember.CallUnary(ctx, req)
}

// RemoveInstallationMember calls tempestvideo.v1.MembersService.RemoveInstallationMember.
func (c *membersServiceClient) RemoveInstallationMember(ctx context.Context, req *connect.Request[tempestvideov1.RemoveInstallationMemberRequest]) (*connect.Response[tempestvideov1.RemoveInstallationMemberResponse], error) {
	return c.removeInstallationMember.CallUnary(ctx, req)
}

// UpdatePendingAccess calls tempestvideo.v1.MembersService.UpdatePendingAccess.
func (c *membersServiceClient) UpdatePendingAccess(ctx context.Context, req *connect.Request[tempestvideov1.UpdatePendingAccessRequest]) (*connect.Response[tempestvideov1.UpdatePendingAccessResponse], error) {
	return c.updatePendingAccess.CallUnary(ctx, req)
}

// CancelPendingAccess calls tempestvideo.v1.MembersService.CancelPendingAccess.
func (c *membersServiceClient) CancelPendingAccess(ctx context.Context, req *connect.Request[tempestvideov1.CancelPendingAccessRequest]) (*connect.Response[tempestvideov1.CancelPendingAccessResponse], error) {
	return c.cancelPendingAccess.CallUnary(ctx, req)
}

// MembersServiceHandler is an implementation of the tempestvideo.v1.MembersService service.
type MembersServiceHandler interface {
	ListTenantAdmins(context.Context, *connect.Request[tempestvideov1.ListTenantAdminsRequest]) (*connect.Response[tempestvideov1.ListTenantAdminsResponse], error)
	AddTenantAdmin(context.Context, *connect.Request[tempestvideov1.AddTenantAdminRequest]) (*connect.Response[tempestvideov1.AddTenantAdminResponse], error)
	RemoveTenantAdmin(context.Context, *connect.Request[tempestvideov1.RemoveTenantAdminRequest]) (*connect.Response[tempestvideov1.RemoveTenantAdminResponse], error)
	ListInstallationMembers(context.Context, *connect.Request[tempestvideov1.ListInstallationMembersRequest]) (*connect.Response[tempestvideov1.ListInstallationMembersResponse], error)
	AddInstallationMember(context.Context, *connect.Request[tempestvideov1.AddInstallationMemberRequest]) (*connect.Response[tempestvideov1.AddInstallationMemberResponse], error)
	UpdateInstallationMember(context.Context, *connect.Request[tempestvideov1.UpdateInstallationMemberRequest]) (*connect.Response[tempestvideov1.UpdateInstallationMemberResponse], error)
	RemoveInstallationMember(context.Context, *connect.Request[tempestvideov1.RemoveInstallationMemberRequest]) (*connect.Response[tempestvideov1.RemoveInstallationMemberResponse], error)
	UpdatePendingAccess(context.Context, *connect.Request[tempestvideov1.UpdatePendingAccessRequest]) (*connect.Response[tempestvideov1.UpdatePendingAccessResponse], error)
	CancelPendingAccess(context.Context, *connect.Request[tempestvideov1.CancelPendingAccessRequest]) (*connect.Response[tempestvideov1.CancelPendingAccessResponse], error)
}

// NewMembersServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMembersServiceHandler(svc MembersServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	membersServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("MembersService").Methods()
	membersServiceListTenantAdminsHandler := connect.NewUnaryHandler(
		MembersServiceListTenantAdminsProcedure,
		svc.ListTenantAdmins,
		connect.WithSchema(membersServiceMethods.ByName("ListTenantAdmins")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceAddTenantAdminHandler := connect.NewUnaryHandler(
		MembersServiceAddTenantAdminProcedure,
		svc.AddTenantAdmin,
		connect.WithSchema(membersServiceMethods.ByName("AddTenantAdmin")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceRemoveTenantAdminHandler := connect.NewUnaryHandler(
		MembersServiceRemoveTenantAdminProcedure,
		svc.RemoveTenantAdmin,
		connect.WithSchema(membersServiceMethods.ByName("RemoveTenantAdmin")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceListInstallationMembersHandler := connect.NewUnaryHandler(
		MembersServiceListInstallationMembersProcedure,
		svc.ListInstallationMembers,
		connect.WithSchema(membersServiceMethods.ByName("ListInstallationMembers")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceAddInstallationMemberHandler := connect.NewUnaryHandler(
		MembersServiceAddInstallationMemberProcedure,
		svc.AddInstallationMember,
		connect.WithSchema(membersServiceMethods.ByName("AddInstallationMember")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceUpdateInstallationMemberHandler := connect.NewUnaryHandler(
		MembersServiceUpdateInstallationMemberProcedure,
		svc.UpdateInstallationMember,
		connect.WithSchema(membersServiceMethods.ByName("UpdateInstallationMember")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceRemoveInstallationMemberHandler := connect.NewUnaryHandler(
		MembersServiceRemoveInstallationMemberProcedure,
		svc.RemoveInstallationMember,
		connect.WithSchema(membersServiceMethods.ByName("RemoveInstallationMember")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceUpdatePendingAccessHandler := connect.NewUnaryHandler(
		MembersServiceUpdatePendingAccessProcedure,
		svc.UpdatePendingAccess,
		connect.WithSchema(membersServiceMethods.ByName("UpdatePendingAccess")),
		connect.WithHandlerOptions(opts...),
	)
	membersServiceCancelPendingAccessHandler := connect.NewUnaryHandler(
		MembersServiceCancelPendingAccessProcedure,
		svc.CancelPendingAccess,
		connect.WithSchema(membersServiceMethods.ByName("CancelPendingAccess")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.MembersService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MembersServiceListTenantAdminsProcedure:
			membersServiceListTenantAdminsHandler.ServeHTTP(w, r)
		case MembersServiceAddTenantAdminProcedure:
			membersServiceAddTenantAdminHandler.ServeHTTP(w, r)
		case MembersServiceRemoveTenantAdminProcedure:
			membersServiceRemoveTenantAdminHandler.ServeHTTP(w, r)
		case MembersServiceListInstallationMembersProcedure:
			membersServiceListInstallationMembersHandler.ServeHTTP(w, r)
		case MembersServiceAddInstallationMemberProcedure:
			membersServiceAddInstallationMemberHandler.ServeHTTP(w, r)
		case MembersServiceUpdateInstallationMemberProcedure:
			membersServiceUpdateInstallationMemberHandler.ServeHTTP(w, r)
		case MembersServiceRemoveInstallationMemberProcedure:
			membersServiceRemoveInstallationMemberHandler.ServeHTTP(w, r)
		case MembersServiceUpdatePendingAccessProcedure:
			membersServiceUpdatePendingAccessHandler.ServeHTTP(w, r)
		case MembersServiceCancelPendingAccessProcedure:
			membersServiceCancelPendingAccessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMembersServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMembersServiceHandler struct{}

func (UnimplementedMembersServiceHandler) ListTenantAdmins(context.Context, *connect.Request[tempestvideov1.ListTenantAdminsRequest]) (*connect.Response[tempestvideov1.ListTenantAdminsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.ListTenantAdmins is not implemented"))
}

func (UnimplementedMembersServiceHandler) AddTenantAdmin(context.Context, *connect.Request[tempestvideov1.AddTenantAdminRequest]) (*connect.Response[tempestvideov1.AddTenantAdminResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.AddTenantAdmin is not implemented"))
}

func (UnimplementedMembersServiceHandler) RemoveTenantAdmin(context.Context, *connect.Request[tempestvideov1.RemoveTenantAdminRequest]) (*connect.Response[tempestvideov1.RemoveTenantAdminResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.RemoveTenantAdmin is not implemented"))
}

func (UnimplementedMembersServiceHandler) ListInstallationMembers(context.Context, *connect.Request[tempestvideov1.ListInstallationMembersRequest]) (*connect.Response[tempestvideov1.ListInstallationMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.ListInstallationMembers is not implemented"))
}

func (UnimplementedMembersServiceHandler) AddInstallationMember(context.Context, *connect.Request[tempestvideov1.AddInstallationMemberRequest]) (*connect.Response[tempestvideov1.AddInstallationMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.AddInstallationMember is not implemented"))
}

func (UnimplementedMembersServiceHandler) UpdateInstallationMember(context.Context, *connect.Request[tempestvideov1.UpdateInstallationMemberRequest]) (*connect.Response[tempestvideov1.UpdateInstallationMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.UpdateInstallationMember is not implemented"))
}

func (UnimplementedMembersServiceHandler) RemoveInstallationMember(context.Context, *connect.Request[tempestvideov1.RemoveInstallationMemberRequest]) (*connect.Response[tempestvideov1.RemoveInstallationMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.RemoveInstallationMember is not implemented"))
}

func (UnimplementedMembersServiceHandler) UpdatePendingAccess(context.Context, *connect.Request[tempestvideov1.UpdatePendingAccessRequest]) (*connect.Response[tempestvideov1.UpdatePendingAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.UpdatePendingAccess is not implemented"))
}

func (UnimplementedMembersServiceHandler) CancelPendingAccess(context.Context, *connect.Request[tempestvideov1.CancelPendingAccessRequest]) (*connect.Response[tempestvideov1.CancelPendingAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.MembersService.CancelPendingAccess is not implemented"))
}

// ConnectorsServiceClient is a client for the tempestvideo.v1.ConnectorsService service.
type ConnectorsServiceClient interface {
	ListConnectors(context.Context, *connect.Request[tempestvideov1.ListConnectorsRequest]) (*connect.Response[tempestvideov1.ListConnectorsResponse], error)
	CreateInstallationConnector(context.Context, *connect.Request[tempestvideov1.CreateInstallationConnectorRequest]) (*connect.Response[tempestvideov1.CreateInstallationConnectorResponse], error)
	RenameConnector(context.Context, *connect.Request[tempestvideov1.RenameConnectorRequest]) (*connect.Response[tempestvideov1.RenameConnectorResponse], error)
	RegenerateLicenseKey(context.Context, *connect.Request[tempestvideov1.RegenerateLicenseKeyRequest]) (*connect.Response[tempestvideov1.RegenerateLicenseKeyResponse], error)
	RevokeConnector(context.Context, *connect.Request[tempestvideov1.RevokeConnectorRequest]) (*connect.Response[tempestvideov1.RevokeConnectorResponse], error)
	DeleteConnector(context.Context, *connect.Request[tempestvideov1.DeleteConnectorRequest]) (*connect.Response[tempestvideov1.DeleteConnectorResponse], error)
}

// NewConnectorsServiceClient constructs a client for the tempestvideo.v1.ConnectorsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectorsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectorsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectorsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ConnectorsService").Methods()
	return &connectorsServiceClient{
		listConnectors: connect.NewClient[tempestvideov1.ListConnectorsRequest, tempestvideov1.ListConnectorsResponse](
			httpClient,
			baseURL+ConnectorsServiceListConnectorsProcedure,
			connect.WithSchema(connectorsServiceMethods.ByName("ListConnectors")),
			connect.WithClientOptions(opts...),
		),
		createInstallationConnector: connect.NewClient[tempestvideov1.CreateInstallationConnectorRequest, tempestvideov1.CreateInstallationConnectorResponse](
			httpClient,
			baseURL+ConnectorsServiceCreateInstallationConnectorProcedure,
			connect.WithSchema(connectorsServiceMethods.ByName("CreateInstallationConnector")),
			connect.WithClientOptions(opts...),
		),
		renameConnector: connect.NewClient[tempestvideov1.RenameConnectorRequest, tempestvideov1.RenameConnectorResponse](
			httpClient,
			baseURL+ConnectorsServiceRenameConnectorProcedure,
			connect.WithSchema(connectorsServiceMethods.ByName("RenameConnector")),
			connect.WithClientOptions(opts...),
		),
		regenerateLicenseKey: connect.NewClient[tempestvideov1.RegenerateLicenseKeyRequest, tempestvideov1.RegenerateLicenseKeyResponse](
			httpClient,
			baseURL+ConnectorsServiceRegenerateLicenseKeyProcedure,
			connect.WithSchema(connectorsServiceMethods.ByName("RegenerateLicenseKey")),
			connect.WithClientOptions(opts...),
		),
		revokeConnector: connect.NewClient[tempestvideov1.RevokeConnectorRequest, tempestvideov1.RevokeConnectorResponse](
			httpClient,
			baseURL+ConnectorsServiceRevokeConnectorProcedure,
			connect.WithSchema(connectorsServiceMethods.ByName("RevokeConnector")),
			connect.WithClientOptions(opts...),
		),
		deleteConnector: connect.NewClient[tempestvideov1.DeleteConnectorRequest, tempestvideov1.DeleteConnectorResponse](
			httpClient,
			baseURL+ConnectorsServiceDeleteConnectorProcedure,
			connect.WithSchema(connectorsServiceMethods.ByName("DeleteConnector")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectorsServiceClient implements ConnectorsServiceClient.
type connectorsServiceClient struct {
	listConnectors              *connect.Client[tempestvideov1.ListConnectorsRequest, tempestvideov1.ListConnectorsResponse]
	createInstallationConnector *connect.Client[tempestvideov1.CreateInstallationConnectorRequest, tempestvideov1.CreateInstallationConnectorResponse]
	renameConnector             *connect.Client[tempestvideov1.RenameConnectorRequest, tempestvideov1.RenameConnectorResponse]
	regenerateLicenseKey        *connect.Client[tempestvideov1.RegenerateLicenseKeyRequest, tempestvideov1.RegenerateLicenseKeyResponse]
	revokeConnector             *connect.Client[tempestvideov1.RevokeConnectorRequest, tempestvideov1.RevokeConnectorResponse]
	deleteConnector             *connect.Client[tempestvideov1.DeleteConnectorRequest, tempestvideov1.DeleteConnectorResponse]
}

// ListConnectors calls tempestvideo.v1.ConnectorsService.ListConnectors.
func (c *connectorsServiceClient) ListConnectors(ctx context.Context, req *connect.Request[tempestvideov1.ListConnectorsRequest]) (*connect.Response[tempestvideov1.ListConnectorsResponse], error) {
	return c.listConnectors.CallUnary(ctx, req)
}

// CreateInstallationConnector calls tempestvideo.v1.ConnectorsService.CreateInstallationConnector.
func (c *connectorsServiceClient) CreateInstallationConnector(ctx context.Context, req *connect.Request[tempestvideov1.CreateInstallationConnectorRequest]) (*connect.Response[tempestvideov1.CreateInstallationConnectorResponse], error) {
	return c.createInstallationConnector.CallUnary(ctx, req)
}

// RenameConnector calls tempestvideo.v1.ConnectorsService.RenameConnector.
func (c *connectorsServiceClient) RenameConnector(ctx context.Context, req *connect.Request[tempestvideov1.RenameConnectorRequest]) (*connect.Response[tempestvideov1.RenameConnectorResponse], error) {
	return c.renameConnector.CallUnary(ctx, req)
}

// RegenerateLicenseKey calls tempestvideo.v1.ConnectorsService.RegenerateLicenseKey.
func (c *connectorsServiceClient) RegenerateLicenseKey(ctx context.Context, req *connect.Request[tempestvideov1.RegenerateLicenseKeyRequest]) (*connect.Response[tempestvideov1.RegenerateLicenseKeyResponse], error) {
	return c.regenerateLicenseKey.CallUnary(ctx, req)
}

// RevokeConnector calls tempestvideo.v1.ConnectorsService.RevokeConnector.
func (c *connectorsServiceClient) RevokeConnector(ctx context.Context, req *connect.Request[tempestvideov1.RevokeConnectorRequest]) (*connect.Response[tempestvideov1.RevokeConnectorResponse], error) {
	return c.revokeConnector.CallUnary(ctx, req)
}

// DeleteConnector calls tempestvideo.v1.ConnectorsService.DeleteConnector.
func (c *connectorsServiceClient) DeleteConnector(ctx context.Context, req *connect.Request[tempestvideov1.DeleteConnectorRequest]) (*connect.Response[tempestvideov1.DeleteConnectorResponse], error) {
	return c.deleteConnector.CallUnary(ctx, req)
}

// ConnectorsServiceHandler is an implementation of the tempestvideo.v1.ConnectorsService service.
type ConnectorsServiceHandler interface {
	ListConnectors(context.Context, *connect.Request[tempestvideov1.ListConnectorsRequest]) (*connect.Response[tempestvideov1.ListConnectorsResponse], error)
	CreateInstallationConnector(context.Context, *connect.Request[tempestvideov1.CreateInstallationConnectorRequest]) (*connect.Response[tempestvideov1.CreateInstallationConnectorResponse], error)
	RenameConnector(context.Context, *connect.Request[tempestvideov1.RenameConnectorRequest]) (*connect.Response[tempestvideov1.RenameConnectorResponse], error)
	RegenerateLicenseKey(context.Context, *connect.Request[tempestvideov1.RegenerateLicenseKeyRequest]) (*connect.Response[tempestvideov1.RegenerateLicenseKeyResponse], error)
	RevokeConnector(context.Context, *connect.Request[tempestvideov1.RevokeConnectorRequest]) (*connect.Response[tempestvideov1.RevokeConnectorResponse], error)
	DeleteConnector(context.Context, *connect.Request[tempestvideov1.DeleteConnectorRequest]) (*connect.Response[tempestvideov1.DeleteConnectorResponse], error)
}

// NewConnectorsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectorsServiceHandler(svc ConnectorsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectorsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ConnectorsService").Methods()
	connectorsServiceListConnectorsHandler := connect.NewUnaryHandler(
		ConnectorsServiceListConnectorsProcedure,
		svc.ListConnectors,
		connect.WithSchema(connectorsServiceMethods.ByName("ListConnectors")),
		connect.WithHandlerOptions(opts...),
	)
	connectorsServiceCreateInstallationConnectorHandler := connect.NewUnaryHandler(
		ConnectorsServiceCreateInstallationConnectorProcedure,
		svc.CreateInstallationConnector,
		connect.WithSchema(connectorsServiceMethods.ByName("CreateInstallationConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorsServiceRenameConnectorHandler := connect.NewUnaryHandler(
		ConnectorsServiceRenameConnectorProcedure,
		svc.RenameConnector,
		connect.WithSchema(connectorsServiceMethods.ByName("RenameConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorsServiceRegenerateLicenseKeyHandler := connect.NewUnaryHandler(
		ConnectorsServiceRegenerateLicenseKeyProcedure,
		svc.RegenerateLicenseKey,
		connect.WithSchema(connectorsServiceMethods.ByName("RegenerateLicenseKey")),
		connect.WithHandlerOptions(opts...),
	)
	connectorsServiceRevokeConnectorHandler := connect.NewUnaryHandler(
		ConnectorsServiceRevokeConnectorProcedure,
		svc.RevokeConnector,
		connect.WithSchema(connectorsServiceMethods.ByName("RevokeConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorsServiceDeleteConnectorHandler := connect.NewUnaryHandler(
		ConnectorsServiceDeleteConnectorProcedure,
		svc.DeleteConnector,
		connect.WithSchema(connectorsServiceMethods.ByName("DeleteConnector")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.ConnectorsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectorsServiceListConnectorsProcedure:
			connectorsServiceListConnectorsHandler.ServeHTTP(w, r)
		case ConnectorsServiceCreateInstallationConnectorProcedure:
			connectorsServiceCreateInstallationConnectorHandler.ServeHTTP(w, r)
		case ConnectorsServiceRenameConnectorProcedure:
			connectorsServiceRenameConnectorHandler.ServeHTTP(w, r)
		case ConnectorsServiceRegenerateLicenseKeyProcedure:
			connectorsServiceRegenerateLicenseKeyHandler.ServeHTTP(w, r)
		case ConnectorsServiceRevokeConnectorProcedure:
			connectorsServiceRevokeConnectorHandler.ServeHTTP(w, r)
		case ConnectorsServiceDeleteConnectorProcedure:
			connectorsServiceDeleteConnectorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectorsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectorsServiceHandler struct{}

func (UnimplementedConnectorsServiceHandler) ListConnectors(context.Context, *connect.Request[tempestvideov1.ListConnectorsRequest]) (*connect.Response[tempestvideov1.ListConnectorsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ConnectorsService.ListConnectors is not implemented"))
}

func (UnimplementedConnectorsServiceHandler) CreateInstallationConnector(context.Context, *connect.Request[tempestvideov1.CreateInstallationConnectorRequest]) (*connect.Response[tempestvideov1.CreateInstallationConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ConnectorsService.CreateInstallationConnector is not implemented"))
}

func (UnimplementedConnectorsServiceHandler) RenameConnector(context.Context, *connect.Request[tempestvideov1.RenameConnectorRequest]) (*connect.Response[tempestvideov1.RenameConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ConnectorsService.RenameConnector is not implemented"))
}

func (UnimplementedConnectorsServiceHandler) RegenerateLicenseKey(context.Context, *connect.Request[tempestvideov1.RegenerateLicenseKeyRequest]) (*connect.Response[tempestvideov1.RegenerateLicenseKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ConnectorsService.RegenerateLicenseKey is not implemented"))
}

func (UnimplementedConnectorsServiceHandler) RevokeConnector(context.Context, *connect.Request[tempestvideov1.RevokeConnectorRequest]) (*connect.Response[tempestvideov1.RevokeConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ConnectorsService.RevokeConnector is not implemented"))
}

func (UnimplementedConnectorsServiceHandler) DeleteConnector(context.Context, *connect.Request[tempestvideov1.DeleteConnectorRequest]) (*connect.Response[tempestvideov1.DeleteConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ConnectorsService.DeleteConnector is not implemented"))
}

// ChannelsServiceClient is a client for the tempestvideo.v1.ChannelsService service.
type ChannelsServiceClient interface {
	ListChannels(context.Context, *connect.Request[tempestvideov1.ListChannelsRequest]) (*connect.Response[tempestvideov1.ListChannelsResponse], error)
	CreateChannel(context.Context, *connect.Request[tempestvideov1.CreateChannelRequest]) (*connect.Response[tempestvideov1.CreateChannelResponse], error)
	UpdateChannel(context.Context, *connect.Request[tempestvideov1.UpdateChannelRequest]) (*connect.Response[tempestvideov1.UpdateChannelResponse], error)
	DeleteChannel(context.Context, *connect.Request[tempestvideov1.DeleteChannelRequest]) (*connect.Response[tempestvideov1.DeleteChannelResponse], error)
	SetChannelIcon(context.Context, *connect.Request[tempestvideov1.SetChannelIconRequest]) (*connect.Response[tempestvideov1.SetChannelIconResponse], error)
	DeleteChannelIcon(context.Context, *connect.Request[tempestvideov1.DeleteChannelIconRequest]) (*connect.Response[tempestvideov1.DeleteChannelIconResponse], error)
}

// NewChannelsServiceClient constructs a client for the tempestvideo.v1.ChannelsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChannelsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChannelsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	channelsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ChannelsService").Methods()
	return &channelsServiceClient{
		listChannels: connect.NewClient[tempestvideov1.ListChannelsRequest, tempestvideov1.ListChannelsResponse](
			httpClient,
			baseURL+ChannelsServiceListChannelsProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("ListChannels")),
			connect.WithClientOptions(opts...),
		),
		createChannel: connect.NewClient[tempestvideov1.CreateChannelRequest, tempestvideov1.CreateChannelResponse](
			httpClient,
			baseURL+ChannelsServiceCreateChannelProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("CreateChannel")),
			connect.WithClientOptions(opts...),
		),
		updateChannel: connect.NewClient[tempestvideov1.UpdateChannelRequest, tempestvideov1.UpdateChannelResponse](
			httpClient,
			baseURL+ChannelsServiceUpdateChannelProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("UpdateChannel")),
			connect.WithClientOptions(opts...),
		),
		deleteChannel: connect.NewClient[tempestvideov1.DeleteChannelRequest, tempestvideov1.DeleteChannelResponse](
			httpClient,
			baseURL+ChannelsServiceDeleteChannelProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("DeleteChannel")),
			connect.WithClientOptions(opts...),
		),
		setChannelIcon: connect.NewClient[tempestvideov1.SetChannelIconRequest, tempestvideov1.SetChannelIconResponse](
			httpClient,
			baseURL+ChannelsServiceSetChannelIconProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("SetChannelIcon")),
			connect.WithClientOptions(opts...),
		),
		deleteChannelIcon: connect.NewClient[tempestvideov1.DeleteChannelIconRequest, tempestvideov1.DeleteChannelIconResponse](
			httpClient,
			baseURL+ChannelsServiceDeleteChannelIconProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("DeleteChannelIcon")),
			connect.WithClientOptions(opts...),
		),
	}
}

// channelsServiceClient implements ChannelsServiceClient.
type channelsServiceClient struct {
	listChannels      *connect.Client[tempestvideov1.ListChannelsRequest, tempestvideov1.ListChannelsResponse]
	createChannel     *connect.Client[tempestvideov1.CreateChannelRequest, tempestvideov1.CreateChannelResponse]
	updateChannel     *connect.Client[tempestvideov1.UpdateChannelRequest, tempestvideov1.UpdateChannelResponse]
	deleteChannel     *connect.Client[tempestvideov1.DeleteChannelRequest, tempestvideov1.DeleteChannelResponse]
	setChannelIcon    *connect.Client[tempestvideov1.SetChannelIconRequest, tempestvideov1.SetChannelIconResponse]
	deleteChannelIcon *connect.Client[tempestvideov1.DeleteChannelIconRequest, tempestvideov1.DeleteChannelIconResponse]
}

// ListChannels calls tempestvideo.v1.ChannelsService.ListChannels.
func (c *channelsServiceClient) ListChannels(ctx context.Context, req *connect.Request[tempestvideov1.ListChannelsRequest]) (*connect.Response[tempestvideov1.ListChannelsResponse], error) {
	return c.listChannels.CallUnary(ctx, req)
}

// CreateChannel calls tempestvideo.v1.ChannelsService.CreateChannel.
func (c *channelsServiceClient) CreateChannel(ctx context.Context, req *connect.Request[tempestvideov1.CreateChannelRequest]) (*connect.Response[tempestvideov1.CreateChannelResponse], error) {
	return c.createChannel.CallUnary(ctx, req)
}

// UpdateChannel calls tempestvideo.v1.ChannelsService.UpdateChannel.
func (c *channelsServiceClient) UpdateChannel(ctx context.Context, req *connect.Request[tempestvideov1.UpdateChannelRequest]) (*connect.Response[tempestvideov1.UpdateChannelResponse], error) {
	return c.updateChannel.CallUnary(ctx, req)
}

// DeleteChannel calls tempestvideo.v1.ChannelsService.DeleteChannel.
func (c *channelsServiceClient) DeleteChannel(ctx context.Context, req *connect.Request[tempestvideov1.DeleteChannelRequest]) (*connect.Response[tempestvideov1.DeleteChannelResponse], error) {
	return c.deleteChannel.CallUnary(ctx, req)
}

// SetChannelIcon calls tempestvideo.v1.ChannelsService.SetChannelIcon.
func (c *channelsServiceClient) SetChannelIcon(ctx context.Context, req *connect.Request[tempestvideov1.SetChannelIconRequest]) (*connect.Response[tempestvideov1.SetChannelIconResponse], error) {
	return c.setChannelIcon.CallUnary(ctx, req)
}

// DeleteChannelIcon calls tempestvideo.v1.ChannelsService.DeleteChannelIcon.
func (c *channelsServiceClient) DeleteChannelIcon(ctx context.Context, req *connect.Request[tempestvideov1.DeleteChannelIconRequest]) (*connect.Response[tempestvideov1.DeleteChannelIconResponse], error) {
	return c.deleteChannelIcon.CallUnary(ctx, req)
}

// ChannelsServiceHandler is an implementation of the tempestvideo.v1.ChannelsService service.
type ChannelsServiceHandler interface {
	ListChannels(context.Context, *connect.Request[tempestvideov1.ListChannelsRequest]) (*connect.Response[tempestvideov1.ListChannelsResponse], error)
	CreateChannel(context.Context, *connect.Request[tempestvideov1.CreateChannelRequest]) (*connect.Response[tempestvideov1.CreateChannelResponse], error)
	UpdateChannel(context.Context, *connect.Request[tempestvideov1.UpdateChannelRequest]) (*connect.Response[tempestvideov1.UpdateChannelResponse], error)
	DeleteChannel(context.Context, *connect.Request[tempestvideov1.DeleteChannelRequest]) (*connect.Response[tempestvideov1.DeleteChannelResponse], error)
	SetChannelIcon(context.Context, *connect.Request[tempestvideov1.SetChannelIconRequest]) (*connect.Response[tempestvideov1.SetChannelIconResponse], error)
	DeleteChannelIcon(context.Context, *connect.Request[tempestvideov1.DeleteChannelIconRequest]) (*connect.Response[tempestvideov1.DeleteChannelIconResponse], error)
}

// NewChannelsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChannelsServiceHandler(svc ChannelsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	channelsServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ChannelsService").Methods()
	channelsServiceListChannelsHandler := connect.NewUnaryHandler(
		ChannelsServiceListChannelsProcedure,
		svc.ListChannels,
		connect.WithSchema(channelsServiceMethods.ByName("ListChannels")),
		connect.WithHandlerOptions(opts...),
	)
	channelsServiceCreateChannelHandler := connect.NewUnaryHandler(
		ChannelsServiceCreateChannelProcedure,
		svc.CreateChannel,
		connect.WithSchema(channelsServiceMethods.ByName("CreateChannel")),
		connect.WithHandlerOptions(opts...),
	)
	channelsServiceUpdateChannelHandler := connect.NewUnaryHandler(
		ChannelsServiceUpdateChannelProcedure,
		svc.UpdateChannel,
		connect.WithSchema(channelsServiceMethods.ByName("UpdateChannel")),
		connect.WithHandlerOptions(opts...),
	)
	channelsServiceDeleteChannelHandler := connect.NewUnaryHandler(
		ChannelsServiceDeleteChannelProcedure,
		svc.DeleteChannel,
		connect.WithSchema(channelsServiceMethods.ByName("DeleteChannel")),
		connect.WithHandlerOptions(opts...),
	)
	channelsServiceSetChannelIconHandler := connect.NewUnaryHandler(
		ChannelsServiceSetChannelIconProcedure,
		svc.SetChannelIcon,
		connect.WithSchema(channelsServiceMethods.ByName("SetChannelIcon")),
		connect.WithHandlerOptions(opts...),
	)
	channelsServiceDeleteChannelIconHandler := connect.NewUnaryHandler(
		ChannelsServiceDeleteChannelIconProcedure,
		svc.DeleteChannelIcon,
		connect.WithSchema(channelsServiceMethods.ByName("DeleteChannelIcon")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.ChannelsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChannelsServiceListChannelsProcedure:
			channelsServiceListChannelsHandler.ServeHTTP(w, r)
		case ChannelsServiceCreateChannelProcedure:
			channelsServiceCreateChannelHandler.ServeHTTP(w, r)
		case ChannelsServiceUpdateChannelProcedure:
			channelsServiceUpdateChannelHandler.ServeHTTP(w, r)
		case ChannelsServiceDeleteChannelProcedure:
			channelsServiceDeleteChannelHandler.ServeHTTP(w, r)
		case ChannelsServiceSetChannelIconProcedure:
			channelsServiceSetChannelIconHandler.ServeHTTP(w, r)
		case ChannelsServiceDeleteChannelIconProcedure:
			channelsServiceDeleteChannelIconHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChannelsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChannelsServiceHandler struct{}

func (UnimplementedChannelsServiceHandler) ListChannels(context.Context, *connect.Request[tempestvideov1.ListChannelsRequest]) (*connect.Response[tempestvideov1.ListChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ChannelsService.ListChannels is not implemented"))
}

func (UnimplementedChannelsServiceHandler) CreateChannel(context.Context, *connect.Request[tempestvideov1.CreateChannelRequest]) (*connect.Response[tempestvideov1.CreateChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ChannelsService.CreateChannel is not implemented"))
}

func (UnimplementedChannelsServiceHandler) UpdateChannel(context.Context, *connect.Request[tempestvideov1.UpdateChannelRequest]) (*connect.Response[tempestvideov1.UpdateChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ChannelsService.UpdateChannel is not implemented"))
}

func (UnimplementedChannelsServiceHandler) DeleteChannel(context.Context, *connect.Request[tempestvideov1.DeleteChannelRequest]) (*connect.Response[tempestvideov1.DeleteChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ChannelsService.DeleteChannel is not implemented"))
}

func (UnimplementedChannelsServiceHandler) SetChannelIcon(context.Context, *connect.Request[tempestvideov1.SetChannelIconRequest]) (*connect.Response[tempestvideov1.SetChannelIconResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ChannelsService.SetChannelIcon is not implemented"))
}

func (UnimplementedChannelsServiceHandler) DeleteChannelIcon(context.Context, *connect.Request[tempestvideov1.DeleteChannelIconRequest]) (*connect.Response[tempestvideov1.DeleteChannelIconResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ChannelsService.DeleteChannelIcon is not implemented"))
}

// DevicesServiceClient is a client for the tempestvideo.v1.DevicesService service.
type DevicesServiceClient interface {
	ListDevices(context.Context, *connect.Request[tempestvideov1.ListDevicesRequest]) (*connect.Response[tempestvideov1.ListDevicesResponse], error)
	CreateDevice(context.Context, *connect.Request[tempestvideov1.CreateDeviceRequest]) (*connect.Response[tempestvideov1.CreateDeviceResponse], error)
	UpdateDevice(context.Context, *connect.Request[tempestvideov1.UpdateDeviceRequest]) (*connect.Response[tempestvideov1.UpdateDeviceResponse], error)
	DeleteDevice(context.Context, *connect.Request[tempestvideov1.DeleteDeviceRequest]) (*connect.Response[tempestvideov1.DeleteDeviceResponse], error)
	SetDeviceChannel(context.Context, *connect.Request[tempestvideov1.SetDeviceChannelRequest]) (*connect.Response[tempestvideov1.SetDeviceChannelResponse], error)
	GetChannelRequest(context.Context, *connect.Request[tempestvideov1.GetChannelRequestRequest]) (*connect.Response[tempestvideov1.GetChannelRequestResponse], error)
	ProvisionDevice(context.Context, *connect.Request[tempestvideov1.ProvisionDeviceRequest]) (*connect.Response[tempestvideov1.ProvisionDeviceResponse], error)
	GetDeviceTask(context.Context, *connect.Request[tempestvideov1.GetDeviceTaskRequest]) (*connect.Response[tempestvideov1.GetDeviceTaskResponse], error)
}

// NewDevicesServiceClient constructs a client for the tempestvideo.v1.DevicesService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDevicesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DevicesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	devicesServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("DevicesService").Methods()
	return &devicesServiceClient{
		listDevices: connect.NewClient[tempestvideov1.ListDevicesRequest, tempestvideov1.ListDevicesResponse](
			httpClient,
			baseURL+DevicesServiceListDevicesProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("ListDevices")),
			connect.WithClientOptions(opts...),
		),
		createDevice: connect.NewClient[tempestvideov1.CreateDeviceRequest, tempestvideov1.CreateDeviceResponse](
			httpClient,
			baseURL+DevicesServiceCreateDeviceProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("CreateDevice")),
			connect.WithClientOptions(opts...),
		),
		updateDevice: connect.NewClient[tempestvideov1.UpdateDeviceRequest, tempestvideov1.UpdateDeviceResponse](
			httpClient,
			baseURL+DevicesServiceUpdateDeviceProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("UpdateDevice")),
			connect.WithClientOptions(opts...),
		),
		deleteDevice: connect.NewClient[tempestvideov1.DeleteDeviceRequest, tempestvideov1.DeleteDeviceResponse](
			httpClient,
			baseURL+DevicesServiceDeleteDeviceProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("DeleteDevice")),
			connect.WithClientOptions(opts...),
		),
		setDeviceChannel: connect.NewClient[tempestvideov1.SetDeviceChannelRequest, tempestvideov1.SetDeviceChannelResponse](
			httpClient,
			baseURL+DevicesServiceSetDeviceChannelProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("SetDeviceChannel")),
			connect.WithClientOptions(opts...),
		),
		getChannelRequest: connect.NewClient[tempestvideov1.GetChannelRequestRequest, tempestvideov1.GetChannelRequestResponse](
			httpClient,
			baseURL+DevicesServiceGetChannelRequestProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("GetChannelRequest")),
			connect.WithClientOptions(opts...),
		),
		provisionDevice: connect.NewClient[tempestvideov1.ProvisionDeviceRequest, tempestvideov1.ProvisionDeviceResponse](
			httpClient,
			baseURL+DevicesServiceProvisionDeviceProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("ProvisionDevice")),
			connect.WithClientOptions(opts...),
		),
		getDeviceTask: connect.NewClient[tempestvideov1.GetDeviceTaskRequest, tempestvideov1.GetDeviceTaskResponse](
			httpClient,
			baseURL+DevicesServiceGetDeviceTaskProcedure,
			connect.WithSchema(devicesServiceMethods.ByName("GetDeviceTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// devicesServiceClient implements DevicesServiceClient.
type devicesServiceClient struct {
	listDevices       *connect.Client[tempestvideov1.ListDevicesRequest, tempestvideov1.ListDevicesResponse]
	createDevice      *connect.Client[tempestvideov1.CreateDeviceRequest, tempestvideov1.CreateDeviceResponse]
	updateDevice      *connect.Client[tempestvideov1.UpdateDeviceRequest, tempestvideov1.UpdateDeviceResponse]
	deleteDevice      *connect.Client[tempestvideov1.DeleteDeviceRequest, tempestvideov1.DeleteDeviceResponse]
	setDeviceChannel  *connect.Client[tempestvideov1.SetDeviceChannelRequest, tempestvideov1.SetDeviceChannelResponse]
	getChannelRequest *connect.Client[tempestvideov1.GetChannelRequestRequest, tempestvideov1.GetChannelRequestResponse]
	provisionDevice   *connect.Client[tempestvideov1.ProvisionDeviceRequest, tempestvideov1.ProvisionDeviceResponse]
	getDeviceTask     *connect.Client[tempestvideov1.GetDeviceTaskRequest, tempestvideov1.GetDeviceTaskResponse]
}

// ListDevices calls tempestvideo.v1.DevicesService.ListDevices.
func (c *devicesServiceClient) ListDevices(ctx context.Context, req *connect.Request[tempestvideov1.ListDevicesRequest]) (*connect.Response[tempestvideov1.ListDevicesResponse], error) {
	return c.listDevices.CallUnary(ctx, req)
}

// CreateDevice calls tempestvideo.v1.DevicesService.CreateDevice.
func (c *devicesServiceClient) CreateDevice(ctx context.Context, req *connect.Request[tempestvideov1.CreateDeviceRequest]) (*connect.Response[tempestvideov1.CreateDeviceResponse], error) {
	return c.createDevice.CallUnary(ctx, req)
}

// UpdateDevice calls tempestvideo.v1.DevicesService.UpdateDevice.
func (c *devicesServiceClient) UpdateDevice(ctx context.Context, req *connect.Request[tempestvideov1.UpdateDeviceRequest]) (*connect.Response[tempestvideov1.UpdateDeviceResponse], error) {
	return c.updateDevice.CallUnary(ctx, req)
}

// DeleteDevice calls tempestvideo.v1.DevicesService.DeleteDevice.
func (c *devicesServiceClient) DeleteDevice(ctx context.Context, req *connect.Request[tempestvideov1.DeleteDeviceRequest]) (*connect.Response[tempestvideov1.DeleteDeviceResponse], error) {
	return c.deleteDevice.CallUnary(ctx, req)
}

// SetDeviceChannel calls tempestvideo.v1.DevicesService.SetDeviceChannel.
func (c *devicesServiceClient) SetDeviceChannel(ctx context.Context, req *connect.Request[tempestvideov1.SetDeviceChannelRequest]) (*connect.Response[tempestvideov1.SetDeviceChannelResponse], error) {
	return c.setDeviceChannel.CallUnary(ctx, req)
}

// GetChannelRequest calls tempestvideo.v1.DevicesService.GetChannelRequest.
func (c *devicesServiceClient) GetChannelRequest(ctx context.Context, req *connect.Request[tempestvideov1.GetChannelRequestRequest]) (*connect.Response[tempestvideov1.GetChannelRequestResponse], error) {
	return c.getChannelRequest.CallUnary(ctx, req)
}

// ProvisionDevice calls tempestvideo.v1.DevicesService.ProvisionDevice.
func (c *devicesServiceClient) ProvisionDevice(ctx context.Context, req *connect.Request[tempestvideov1.ProvisionDeviceRequest]) (*connect.Response[tempestvideov1.ProvisionDeviceResponse], error) {
	return c.provisionDevice.CallUnary(ctx, req)
}

// GetDeviceTask calls tempestvideo.v1.DevicesService.GetDeviceTask.
func (c *devicesServiceClient) GetDeviceTask(ctx context.Context, req *connect.Request[tempestvideov1.GetDeviceTaskRequest]) (*connect.Response[tempestvideov1.GetDeviceTaskResponse], error) {
	return c.getDeviceTask.CallUnary(ctx, req)
}

// DevicesServiceHandler is an implementation of the tempestvideo.v1.DevicesService service.
type DevicesServiceHandler interface {
	ListDevices(context.Context, *connect.Request[tempestvideov1.ListDevicesRequest]) (*connect.Response[tempestvideov1.ListDevicesResponse], error)
	CreateDevice(context.Context, *connect.Request[tempestvideov1.CreateDeviceRequest]) (*connect.Response[tempestvideov1.CreateDeviceResponse], error)
	UpdateDevice(context.Context, *connect.Request[tempestvideov1.UpdateDeviceRequest]) (*connect.Response[tempestvideov1.UpdateDeviceResponse], error)
	DeleteDevice(context.Context, *connect.Request[tempestvideov1.DeleteDeviceRequest]) (*connect.Response[tempestvideov1.DeleteDeviceResponse], error)
	SetDeviceChannel(context.Context, *connect.Request[tempestvideov1.SetDeviceChannelRequest]) (*connect.Response[tempestvideov1.SetDeviceChannelResponse], error)
	GetChannelRequest(context.Context, *connect.Request[tempestvideov1.GetChannelRequestRequest]) (*connect.Response[tempestvideov1.GetChannelRequestResponse], error)
	ProvisionDevice(context.Context, *connect.Request[tempestvideov1.ProvisionDeviceRequest]) (*connect.Response[tempestvideov1.ProvisionDeviceResponse], error)
	GetDeviceTask(context.Context, *connect.Request[tempestvideov1.GetDeviceTaskRequest]) (*connect.Response[tempestvideov1.GetDeviceTaskResponse], error)
}

// NewDevicesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDevicesServiceHandler(svc DevicesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	devicesServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("DevicesService").Methods()
	devicesServiceListDevicesHandler := connect.NewUnaryHandler(
		DevicesServiceListDevicesProcedure,
		svc.ListDevices,
		connect.WithSchema(devicesServiceMethods.ByName("ListDevices")),
		connect.WithHandlerOptions(opts...),
	)
	devicesServiceCreateDeviceHandler := connect.NewUnaryHandler(
		DevicesServiceCreateDeviceProcedure,
		svc.CreateDevice,
		connect.WithSchema(devicesServiceMethods.ByName("CreateDevice")),
		connect.WithHandlerOptions(opts...),
	)
	devicesServiceUpdateDeviceHandler := connect.NewUnaryHandler(
		DevicesServiceUpdateDeviceProcedure,
		svc.UpdateDevice,
		connect.WithSchema(devicesServiceMethods.ByName("UpdateDevice")),
		connect.WithHandlerOptions(opts...),
	)
	devicesServiceDeleteDeviceHandler := connect.NewUnaryHandler(
		DevicesServiceDeleteDeviceProcedure,
		svc.DeleteDevice,
		connect.WithSchema(devicesServiceMethods.ByName("DeleteDevice")),
		connect.WithHandlerOptions(opts...),
	)
	devicesServiceSetDeviceChannelHandler := connect.NewUnaryHandler(
		DevicesServiceSetDeviceChannelProcedure,
		svc.SetDeviceChannel,
		connect.WithSchema(devicesServiceMethods.ByName("SetDeviceChannel")),
		connect.WithHandlerOptions(opts...),
	)
	devicesServiceGetChannelRequestHandler := connect.NewUnaryHandler(
		DevicesServiceGetChannelRequestProcedure,
		svc.GetChannelRequest,
		connect.WithSchema(devicesServiceMethods.ByName("GetChannelRequest")),
		connect.WithHandlerOptions(opts...),
	)
	devicesServiceProvisionDeviceHandler := connect.NewUnaryHandler(
		DevicesServiceProvisionDeviceProcedure,
		svc.ProvisionDevice,
		connect.WithSchema(devicesServiceMethods.ByName("ProvisionDevice")),
		connect.WithHandlerOptions(opts...),
	)
	devicesServiceGetDeviceTaskHandler := connect.NewUnaryHandler(
		DevicesServiceGetDeviceTaskProcedure,
		svc.GetDeviceTask,
		connect.WithSchema(devicesServiceMethods.ByName("GetDeviceTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.DevicesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DevicesServiceListDevicesProcedure:
			devicesServiceListDevicesHandler.ServeHTTP(w, r)
		case DevicesServiceCreateDeviceProcedure:
			devicesServiceCreateDeviceHandler.ServeHTTP(w, r)
		case DevicesServiceUpdateDeviceProcedure:
			devicesServiceUpdateDeviceHandler.ServeHTTP(w, r)
		case DevicesServiceDeleteDeviceProcedure:
			devicesServiceDeleteDeviceHandler.ServeHTTP(w, r)
		case DevicesServiceSetDeviceChannelProcedure:
			devicesServiceSetDeviceChannelHandler.ServeHTTP(w, r)
		case DevicesServiceGetChannelRequestProcedure:
			devicesServiceGetChannelRequestHandler.ServeHTTP(w, r)
		case DevicesServiceProvisionDeviceProcedure:
			devicesServiceProvisionDeviceHandler.ServeHTTP(w, r)
		case DevicesServiceGetDeviceTaskProcedure:
			devicesServiceGetDeviceTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDevicesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDevicesServiceHandler struct{}

func (UnimplementedDevicesServiceHandler) ListDevices(context.Context, *connect.Request[tempestvideov1.ListDevicesRequest]) (*connect.Response[tempestvideov1.ListDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.ListDevices is not implemented"))
}

func (UnimplementedDevicesServiceHandler) CreateDevice(context.Context, *connect.Request[tempestvideov1.CreateDeviceRequest]) (*connect.Response[tempestvideov1.CreateDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.CreateDevice is not implemented"))
}

func (UnimplementedDevicesServiceHandler) UpdateDevice(context.Context, *connect.Request[tempestvideov1.UpdateDeviceRequest]) (*connect.Response[tempestvideov1.UpdateDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.UpdateDevice is not implemented"))
}

func (UnimplementedDevicesServiceHandler) DeleteDevice(context.Context, *connect.Request[tempestvideov1.DeleteDeviceRequest]) (*connect.Response[tempestvideov1.DeleteDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.DeleteDevice is not implemented"))
}

func (UnimplementedDevicesServiceHandler) SetDeviceChannel(context.Context, *connect.Request[tempestvideov1.SetDeviceChannelRequest]) (*connect.Response[tempestvideov1.SetDeviceChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.SetDeviceChannel is not implemented"))
}

func (UnimplementedDevicesServiceHandler) GetChannelRequest(context.Context, *connect.Request[tempestvideov1.GetChannelRequestRequest]) (*connect.Response[tempestvideov1.GetChannelRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.GetChannelRequest is not implemented"))
}

func (UnimplementedDevicesServiceHandler) ProvisionDevice(context.Context, *connect.Request[tempestvideov1.ProvisionDeviceRequest]) (*connect.Response[tempestvideov1.ProvisionDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.ProvisionDevice is not implemented"))
}

func (UnimplementedDevicesServiceHandler) GetDeviceTask(context.Context, *connect.Request[tempestvideov1.GetDeviceTaskRequest]) (*connect.Response[tempestvideov1.GetDeviceTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.DevicesService.GetDeviceTask is not implemented"))
}

// ApiKeysServiceClient is a client for the tempestvideo.v1.ApiKeysService service.
type ApiKeysServiceClient interface {
	CreateApiKey(context.Context, *connect.Request[tempestvideov1.CreateApiKeyRequest]) (*connect.Response[tempestvideov1.CreateApiKeyResponse], error)
	ListApiKeys(context.Context, *connect.Request[tempestvideov1.ListApiKeysRequest]) (*connect.Response[tempestvideov1.ListApiKeysResponse], error)
	DeleteApiKey(context.Context, *connect.Request[tempestvideov1.DeleteApiKeyRequest]) (*connect.Response[tempestvideov1.DeleteApiKeyResponse], error)
}

// NewApiKeysServiceClient constructs a client for the tempestvideo.v1.ApiKeysService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApiKeysServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApiKeysServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	apiKeysServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ApiKeysService").Methods()
	return &apiKeysServiceClient{
		createApiKey: connect.NewClient[tempestvideov1.CreateApiKeyRequest, tempestvideov1.CreateApiKeyResponse](
			httpClient,
			baseURL+ApiKeysServiceCreateApiKeyProcedure,
			connect.WithSchema(apiKeysServiceMethods.ByName("CreateApiKey")),
			connect.WithClientOptions(opts...),
		),
		listApiKeys: connect.NewClient[tempestvideov1.ListApiKeysRequest, tempestvideov1.ListApiKeysResponse](
			httpClient,
			baseURL+ApiKeysServiceListApiKeysProcedure,
			connect.WithSchema(apiKeysServiceMethods.ByName("ListApiKeys")),
			connect.WithClientOptions(opts...),
		),
		deleteApiKey: connect.NewClient[tempestvideov1.DeleteApiKeyRequest, tempestvideov1.DeleteApiKeyResponse](
			httpClient,
			baseURL+ApiKeysServiceDeleteApiKeyProcedure,
			connect.WithSchema(apiKeysServiceMethods.ByName("DeleteApiKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// apiKeysServiceClient implements ApiKeysServiceClient.
type apiKeysServiceClient struct {
	createApiKey *connect.Client[tempestvideov1.CreateApiKeyRequest, tempestvideov1.CreateApiKeyResponse]
	listApiKeys  *connect.Client[tempestvideov1.ListApiKeysRequest, tempestvideov1.ListApiKeysResponse]
	deleteApiKey *connect.Client[tempestvideov1.DeleteApiKeyRequest, tempestvideov1.DeleteApiKeyResponse]
}

// CreateApiKey calls tempestvideo.v1.ApiKeysService.CreateApiKey.
func (c *apiKeysServiceClient) CreateApiKey(ctx context.Context, req *connect.Request[tempestvideov1.CreateApiKeyRequest]) (*connect.Response[tempestvideov1.CreateApiKeyResponse], error) {
	return c.createApiKey.CallUnary(ctx, req)
}

// ListApiKeys calls tempestvideo.v1.ApiKeysService.ListApiKeys.
func (c *apiKeysServiceClient) ListApiKeys(ctx context.Context, req *connect.Request[tempestvideov1.ListApiKeysRequest]) (*connect.Response[tempestvideov1.ListApiKeysResponse], error) {
	return c.listApiKeys.CallUnary(ctx, req)
}

// DeleteApiKey calls tempestvideo.v1.ApiKeysService.DeleteApiKey.
func (c *apiKeysServiceClient) DeleteApiKey(ctx context.Context, req *connect.Request[tempestvideov1.DeleteApiKeyRequest]) (*connect.Response[tempestvideov1.DeleteApiKeyResponse], error) {
	return c.deleteApiKey.CallUnary(ctx, req)
}

// ApiKeysServiceHandler is an implementation of the tempestvideo.v1.ApiKeysService service.
type ApiKeysServiceHandler interface {
	CreateApiKey(context.Context, *connect.Request[tempestvideov1.CreateApiKeyRequest]) (*connect.Response[tempestvideov1.CreateApiKeyResponse], error)
	ListApiKeys(context.Context, *connect.Request[tempestvideov1.ListApiKeysRequest]) (*connect.Response[tempestvideov1.ListApiKeysResponse], error)
	DeleteApiKey(context.Context, *connect.Request[tempestvideov1.DeleteApiKeyRequest]) (*connect.Response[tempestvideov1.DeleteApiKeyResponse], error)
}

// NewApiKeysServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApiKeysServiceHandler(svc ApiKeysServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	apiKeysServiceMethods := tempestvideov1.File_tempestvideo_v1_api_proto.Services().ByName("ApiKeysService").Methods()
	apiKeysServiceCreateApiKeyHandler := connect.NewUnaryHandler(
		ApiKeysServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(apiKeysServiceMethods.ByName("CreateApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	apiKeysServiceListApiKeysHandler := connect.NewUnaryHandler(
		ApiKeysServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(apiKeysServiceMethods.ByName("ListApiKeys")),
		connect.WithHandlerOptions(opts...),
	)
	apiKeysServiceDeleteApiKeyHandler := connect.NewUnaryHandler(
		ApiKeysServiceDeleteApiKeyProcedure,
		svc.DeleteApiKey,
		connect.WithSchema(apiKeysServiceMethods.ByName("DeleteApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tempestvideo.v1.ApiKeysService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApiKeysServiceCreateApiKeyProcedure:
			apiKeysServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case ApiKeysServiceListApiKeysProcedure:
			apiKeysServiceListApiKeysHandler.ServeHTTP(w, r)
		case ApiKeysServiceDeleteApiKeyProcedure:
			apiKeysServiceDeleteApiKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApiKeysServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApiKeysServiceHandler struct{}

func (UnimplementedApiKeysServiceHandler) CreateApiKey(context.Context, *connect.Request[tempestvideov1.CreateApiKeyRequest]) (*connect.Response[tempestvideov1.CreateApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ApiKeysService.CreateApiKey is not implemented"))
}

func (UnimplementedApiKeysServiceHandler) ListApiKeys(context.Context, *connect.Request[tempestvideov1.ListApiKeysRequest]) (*connect.Response[tempestvideov1.ListApiKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ApiKeysService.ListApiKeys is not implemented"))
}

func (UnimplementedApiKeysServiceHandler) DeleteApiKey(context.Context, *connect.Request[tempestvideov1.DeleteApiKeyRequest]) (*connect.Response[tempestvideov1.DeleteApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tempestvideo.v1.ApiKeysService.DeleteApiKey is not implemented"))
}
